### ISSUE TITLE
Support for xcworkspace

### ISSUE THREAD

**Issue by 4brunu** [lvsti/Bridgecraft#2]
Currently this only supports *.xcodeproj files, it would be great to support also *.xcworkspace.

**Comment by lvsti** [comment]
Makes sense, but somehow we need to get to specifying a target. Workspace + scheme is still not sufficient because a scheme may build multiple targets. I've tried to dump the build settings with xcodebuild and only the first target is returned:

```
$ xcodebuild -showBuildSettings -workspace Carthage/Checkouts/Quick/Quick.xcworkspace -scheme Nimble-iOS
Build settings for action build and target Nimble-iOS:
    ACTION = build
    ...
    TARGETNAME = Nimble-iOS
    ...
```

The "Nimble-iOS" scheme also builds the "Nimble-iOSTests" target but that's nowhere to be found here. This is a problem if we want to generate an interface for the test target bridging header.

Another issue is that the current implementation requires a project file to include the dummy and trigger a fake build in order to get the compiler flags. (This might be achieved differently in the future but right now I don't know a way around it.) So even if we parse the xcworkspacedata file, the project name must still be specified (a workspace may contain many) to not be ambiguous.

What do you think?

**Comment by 4brunu** [comment]
I see, that makes things a bit more complicated.

I asked this, because I had an error using Bridgecraft in a project that contains cocoapods dependencies, and I thought the error was related to using the *.xcodeproj file instead of *.xcworkspace.

But after more testing I saw that the error was related to https://github.com/lvsti/Bridgecraft/issues/8.
I change the `xcodebuild` invocation to use the simulator instead of the real device and it worked.

So if this always works with the *.xcodeproj I have no problem on Bridgecraft only supporting only *.xcodeproj files.

**Comment by lvsti** [comment]
I'm closing this for now, feel free to reopen if you've found a sensible way around
